# Copyright (c) 2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
cases:
    - decl: |-
          const s = 'XYZ'
      use: |-
          // test resolving path
          const r: Promise<string> = new Promise<string>(
              (resolve: (p: string) => void, reject: (p: Error) => void): void => {
                  if (s == 'XYZ') {
                      resolve(s)
                  } else {
                      reject(new Error('ABC'))
                  }
              }
          )
          arktest.assertTrue((await r) == 'XYZ')

    - decl: |-
          const s = 'XYZ'
      use: |-
          // test rejection path
          const r: Promise<string> = new Promise<string>(
              (resolve: (p: string) => void, reject: (p: Error) => void): void => {
                  if (s != 'XYZ') {
                      resolve(s)
                  } else {
                      reject(new Error('ABC'))
                  }
              }
          )

          try {
              await r
              arktest.assertTrue(false)
          } catch (e) {
              if (e instanceof Error)
                  arktest.assertTrue((e as Error).message == 'ABC')
          }

    - decl: |-
          const s = 'XYZ'
      use: |-
          // test throw from resolving path
          const r: Promise<string> = new Promise<string>(
              (resolve: (p: string) => void, reject: (p: Error) => void): void => {
                  if (s == 'XYZ') {
                      throw new Error(s)
                  } else {
                      reject(new Error('ABC'))
                  }
              }
          )

          try {
              await r
              arktest.assertTrue(false)
          } catch (e) {
              if (e instanceof Error)
                  arktest.assertTrue((e as Error).message == 'XYZ')
          } 
          
    - decl: |-
          const initVal: number = 1.0
      use: |-
          // test then chain, resolved
          const r: Promise<number> = new Promise<number>(
              (resolve: (p: number) => void, reject: (p: Error) => void): void => {
                   resolve(initVal)
              }
          ).then<number>(
              (p: number): number => {
                  return p + 10.0
              }
          ).then<number>(
              (p: number): number => {
                  return p + 100.0
              }
          )
          arktest.assertTrue((await r) == 111.0)

    - decl: |-
      use: |-
          // test catch chain
          const r: Promise<number|Error> = new Promise<number|Error>(
              (resolve: (p: number) => void, reject: (p: Error) => void): void => {
                  reject(new Error('A'))
              }
          ).catch<number|Error>(
              (p: Error): void => {
                  if (p instanceof Error) throw new Error((p as Error).message + 'B')
              }
          ).catch<number|Error>(
              (p: Error): string => {
                  if (p instanceof Error) throw new Error((p as Error).message + 'C')
              }
          )

          try {
              await r
              arktest.assertTrue(false)
          } catch (e) {
              if (e instanceof Error)
                  arktest.assertTrue((e as Error).message == 'ABC')
          } 

    - decl: |-
      use: |-
          // test mixed then and catch chain
          const r: Promise<string> = new Promise<string>(
              (resolve: (p: string) => void, reject: (p: Error) => void): void => {
                  resolve('A')
              }
          ).catch<string>(  // skipped
              (p: Error|string): string => {
                  if (p instanceof Error) throw new Error((p as Error).message + 'C')
                  return 'D'
              }
          ).then<string>(
              (p: string): string => {
                  return p + 'E'
              },
              (p: Error): string => {
                  return ''
              }
          ).then<string>(
              (p: string): string => {
                  throw new Error(p + 'F')
              },
              (p: Error): string => {
                  return ''
              }
          ).then<string>(  // skipped
              (p: string): string => {
                  return p + 'H'
              }
          ).then<string>(
              (p: string): string => {
                  return p + 'I'
              },
              (p: Error): string => {
                  if (p instanceof Error) throw new Error (p.message + 'J')
                  return 'K'
              }
          )

          try {
              await r
              arktest.assertTrue(false)
          } catch (e) {
              if (e instanceof Error)
                  arktest.assertTrue((e as Error).message == 'AEFJ')
          } 

    - decl: |-
      use: |-
          // ensure verify succeed
          const r1: Promise<string> = new Promise<string>(
              (resolve: (p: string) => void, reject: (p: Error) => void): void => {
                  resolve("Async Data")
              }
          ).then(
              (data:string) => "test"
          );
          await r1;

          const r2: Promise<string> = new Promise<string>(
              (resolve: (p: string) => void, reject: (p: Error) => void): void => {
                  resolve("Async Data")
              }
          ).then(
              (data:string) => { return "test" }
          );
          await r2;
          
          arktest.assertTrue(true);